services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - shared-network

  kafka:
    image: docker.io/bitnami/kafka:2.8
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=CLIENT://0.0.0.0:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - shared-network

  sensor-sim:
    image: sensor-sim:latest
    build:
      context: ../sensor-sim
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - shared-network
    env_file:
      - ./.env
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_BROKER=localhost:9092

  pathfinding:
    image: pathfinding:latest
    build:
      context: ../pathfinding
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - shared-network
    depends_on:
      - kafka
      - zookeeper
    env_file:
      - ./.env
    environment:
      - KAFKA_BROKER=localhost:9092

  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - shared-network
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - sensor-sim
      - pathfinding

  test-runner:
    image: test-runner:latest
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - shared-network
    depends_on:
      - gateway
      - sensor-sim
      - pathfinding
    command: ["python", "-m", "pytest", "--cov=app", "--cov-branch", "app/test/e2e"]

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  shared-network:
    name: shared-network
    driver: bridge
